// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spawnersvc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeSpec struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Instance             string            `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	DiskSize             int32             `protobuf:"varint,3,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	HostName             string            `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	State                string            `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Uuid                 string            `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IpAddr               string            `protobuf:"bytes,7,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	Availabilityzone     string            `protobuf:"bytes,8,opt,name=availabilityzone,proto3" json:"availabilityzone,omitempty"`
	ClusterId            string            `protobuf:"bytes,9,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	Labels               map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeSpec) Reset()         { *m = NodeSpec{} }
func (m *NodeSpec) String() string { return proto.CompactTextString(m) }
func (*NodeSpec) ProtoMessage()    {}
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{0}
}

func (m *NodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSpec.Unmarshal(m, b)
}
func (m *NodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSpec.Marshal(b, m, deterministic)
}
func (m *NodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpec.Merge(m, src)
}
func (m *NodeSpec) XXX_Size() int {
	return xxx_messageInfo_NodeSpec.Size(m)
}
func (m *NodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpec proto.InternalMessageInfo

func (m *NodeSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeSpec) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *NodeSpec) GetDiskSize() int32 {
	if m != nil {
		return m.DiskSize
	}
	return 0
}

func (m *NodeSpec) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *NodeSpec) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *NodeSpec) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *NodeSpec) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

func (m *NodeSpec) GetAvailabilityzone() string {
	if m != nil {
		return m.Availabilityzone
	}
	return ""
}

func (m *NodeSpec) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *NodeSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ClusterRequest struct {
	ClusterName          string            `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Provider             string            `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Node                 *NodeSpec         `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClusterRequest) Reset()         { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()    {}
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{1}
}

func (m *ClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRequest.Unmarshal(m, b)
}
func (m *ClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRequest.Merge(m, src)
}
func (m *ClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRequest.Size(m)
}
func (m *ClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRequest proto.InternalMessageInfo

func (m *ClusterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ClusterRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ClusterRequest) GetNode() *NodeSpec {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ClusterRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type GetClusterRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterRequest) Reset()         { *m = GetClusterRequest{} }
func (m *GetClusterRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterRequest) ProtoMessage()    {}
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{2}
}

func (m *GetClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterRequest.Unmarshal(m, b)
}
func (m *GetClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterRequest.Merge(m, src)
}
func (m *GetClusterRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterRequest.Size(m)
}
func (m *GetClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterRequest proto.InternalMessageInfo

func (m *GetClusterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type GetClustersRequest struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClustersRequest) Reset()         { *m = GetClustersRequest{} }
func (m *GetClustersRequest) String() string { return proto.CompactTextString(m) }
func (*GetClustersRequest) ProtoMessage()    {}
func (*GetClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{3}
}

func (m *GetClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersRequest.Unmarshal(m, b)
}
func (m *GetClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersRequest.Marshal(b, m, deterministic)
}
func (m *GetClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersRequest.Merge(m, src)
}
func (m *GetClustersRequest) XXX_Size() int {
	return xxx_messageInfo_GetClustersRequest.Size(m)
}
func (m *GetClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersRequest proto.InternalMessageInfo

func (m *GetClustersRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *GetClustersRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GetClustersRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type ClusterSpec struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId            string      `protobuf:"bytes,2,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	NodeSpec             []*NodeSpec `protobuf:"bytes,3,rep,name=nodeSpec,proto3" json:"nodeSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClusterSpec) Reset()         { *m = ClusterSpec{} }
func (m *ClusterSpec) String() string { return proto.CompactTextString(m) }
func (*ClusterSpec) ProtoMessage()    {}
func (*ClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{4}
}

func (m *ClusterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterSpec.Unmarshal(m, b)
}
func (m *ClusterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterSpec.Marshal(b, m, deterministic)
}
func (m *ClusterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSpec.Merge(m, src)
}
func (m *ClusterSpec) XXX_Size() int {
	return xxx_messageInfo_ClusterSpec.Size(m)
}
func (m *ClusterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSpec proto.InternalMessageInfo

func (m *ClusterSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterSpec) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterSpec) GetNodeSpec() []*NodeSpec {
	if m != nil {
		return m.NodeSpec
	}
	return nil
}

type GetClustersResponse struct {
	Clusters             []*ClusterSpec `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetClustersResponse) Reset()         { *m = GetClustersResponse{} }
func (m *GetClustersResponse) String() string { return proto.CompactTextString(m) }
func (*GetClustersResponse) ProtoMessage()    {}
func (*GetClustersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{5}
}

func (m *GetClustersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersResponse.Unmarshal(m, b)
}
func (m *GetClustersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersResponse.Marshal(b, m, deterministic)
}
func (m *GetClustersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersResponse.Merge(m, src)
}
func (m *GetClustersResponse) XXX_Size() int {
	return xxx_messageInfo_GetClustersResponse.Size(m)
}
func (m *GetClustersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersResponse proto.InternalMessageInfo

func (m *GetClustersResponse) GetClusters() []*ClusterSpec {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type ClusterResponse struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	NodeGroupName        string   `protobuf:"bytes,2,opt,name=nodeGroupName,proto3" json:"nodeGroupName,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterResponse) Reset()         { *m = ClusterResponse{} }
func (m *ClusterResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterResponse) ProtoMessage()    {}
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{6}
}

func (m *ClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterResponse.Unmarshal(m, b)
}
func (m *ClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterResponse.Marshal(b, m, deterministic)
}
func (m *ClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterResponse.Merge(m, src)
}
func (m *ClusterResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterResponse.Size(m)
}
func (m *ClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterResponse proto.InternalMessageInfo

func (m *ClusterResponse) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterResponse) GetNodeGroupName() string {
	if m != nil {
		return m.NodeGroupName
	}
	return ""
}

func (m *ClusterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ClusterStatusRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterStatusRequest) Reset()         { *m = ClusterStatusRequest{} }
func (m *ClusterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterStatusRequest) ProtoMessage()    {}
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{7}
}

func (m *ClusterStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterStatusRequest.Unmarshal(m, b)
}
func (m *ClusterStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterStatusRequest.Marshal(b, m, deterministic)
}
func (m *ClusterStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatusRequest.Merge(m, src)
}
func (m *ClusterStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterStatusRequest.Size(m)
}
func (m *ClusterStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatusRequest proto.InternalMessageInfo

func (m *ClusterStatusRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type ClusterStatusResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterStatusResponse) Reset()         { *m = ClusterStatusResponse{} }
func (m *ClusterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterStatusResponse) ProtoMessage()    {}
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{8}
}

func (m *ClusterStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterStatusResponse.Unmarshal(m, b)
}
func (m *ClusterStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterStatusResponse.Marshal(b, m, deterministic)
}
func (m *ClusterStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatusResponse.Merge(m, src)
}
func (m *ClusterStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterStatusResponse.Size(m)
}
func (m *ClusterStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatusResponse proto.InternalMessageInfo

func (m *ClusterStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ClusterStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AddTokenRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTokenRequest) Reset()         { *m = AddTokenRequest{} }
func (m *AddTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AddTokenRequest) ProtoMessage()    {}
func (*AddTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{9}
}

func (m *AddTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTokenRequest.Unmarshal(m, b)
}
func (m *AddTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTokenRequest.Marshal(b, m, deterministic)
}
func (m *AddTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTokenRequest.Merge(m, src)
}
func (m *AddTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AddTokenRequest.Size(m)
}
func (m *AddTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTokenRequest proto.InternalMessageInfo

func (m *AddTokenRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *AddTokenRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type AddTokenResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTokenResponse) Reset()         { *m = AddTokenResponse{} }
func (m *AddTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AddTokenResponse) ProtoMessage()    {}
func (*AddTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{10}
}

func (m *AddTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTokenResponse.Unmarshal(m, b)
}
func (m *AddTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTokenResponse.Marshal(b, m, deterministic)
}
func (m *AddTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTokenResponse.Merge(m, src)
}
func (m *AddTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AddTokenResponse.Size(m)
}
func (m *AddTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTokenResponse proto.InternalMessageInfo

func (m *AddTokenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AddTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetTokenRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{11}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *GetTokenRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RancherServer        string   `protobuf:"bytes,2,opt,name=rancherServer,proto3" json:"rancherServer,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{12}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetTokenResponse) GetRancherServer() string {
	if m != nil {
		return m.RancherServer
	}
	return ""
}

func (m *GetTokenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AddRoute53RecordRequest struct {
	DnsName              string   `protobuf:"bytes,1,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	RecordName           string   `protobuf:"bytes,2,opt,name=recordName,proto3" json:"recordName,omitempty"`
	RegionName           string   `protobuf:"bytes,3,opt,name=regionName,proto3" json:"regionName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoute53RecordRequest) Reset()         { *m = AddRoute53RecordRequest{} }
func (m *AddRoute53RecordRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoute53RecordRequest) ProtoMessage()    {}
func (*AddRoute53RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{13}
}

func (m *AddRoute53RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoute53RecordRequest.Unmarshal(m, b)
}
func (m *AddRoute53RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoute53RecordRequest.Marshal(b, m, deterministic)
}
func (m *AddRoute53RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoute53RecordRequest.Merge(m, src)
}
func (m *AddRoute53RecordRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoute53RecordRequest.Size(m)
}
func (m *AddRoute53RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoute53RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoute53RecordRequest proto.InternalMessageInfo

func (m *AddRoute53RecordRequest) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

func (m *AddRoute53RecordRequest) GetRecordName() string {
	if m != nil {
		return m.RecordName
	}
	return ""
}

func (m *AddRoute53RecordRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

type AddRoute53RecordResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoute53RecordResponse) Reset()         { *m = AddRoute53RecordResponse{} }
func (m *AddRoute53RecordResponse) String() string { return proto.CompactTextString(m) }
func (*AddRoute53RecordResponse) ProtoMessage()    {}
func (*AddRoute53RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{14}
}

func (m *AddRoute53RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoute53RecordResponse.Unmarshal(m, b)
}
func (m *AddRoute53RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoute53RecordResponse.Marshal(b, m, deterministic)
}
func (m *AddRoute53RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoute53RecordResponse.Merge(m, src)
}
func (m *AddRoute53RecordResponse) XXX_Size() int {
	return xxx_messageInfo_AddRoute53RecordResponse.Size(m)
}
func (m *AddRoute53RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoute53RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoute53RecordResponse proto.InternalMessageInfo

func (m *AddRoute53RecordResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AddRoute53RecordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NodeSpawnRequest struct {
	ClusterName          string    `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	NodeSpec             *NodeSpec `protobuf:"bytes,2,opt,name=nodeSpec,proto3" json:"nodeSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NodeSpawnRequest) Reset()         { *m = NodeSpawnRequest{} }
func (m *NodeSpawnRequest) String() string { return proto.CompactTextString(m) }
func (*NodeSpawnRequest) ProtoMessage()    {}
func (*NodeSpawnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{15}
}

func (m *NodeSpawnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSpawnRequest.Unmarshal(m, b)
}
func (m *NodeSpawnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSpawnRequest.Marshal(b, m, deterministic)
}
func (m *NodeSpawnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpawnRequest.Merge(m, src)
}
func (m *NodeSpawnRequest) XXX_Size() int {
	return xxx_messageInfo_NodeSpawnRequest.Size(m)
}
func (m *NodeSpawnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpawnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpawnRequest proto.InternalMessageInfo

func (m *NodeSpawnRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *NodeSpawnRequest) GetNodeSpec() *NodeSpec {
	if m != nil {
		return m.NodeSpec
	}
	return nil
}

type NodeSpawnResponse struct {
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeSpawnResponse) Reset()         { *m = NodeSpawnResponse{} }
func (m *NodeSpawnResponse) String() string { return proto.CompactTextString(m) }
func (*NodeSpawnResponse) ProtoMessage()    {}
func (*NodeSpawnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{16}
}

func (m *NodeSpawnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSpawnResponse.Unmarshal(m, b)
}
func (m *NodeSpawnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSpawnResponse.Marshal(b, m, deterministic)
}
func (m *NodeSpawnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpawnResponse.Merge(m, src)
}
func (m *NodeSpawnResponse) XXX_Size() int {
	return xxx_messageInfo_NodeSpawnResponse.Size(m)
}
func (m *NodeSpawnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpawnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpawnResponse proto.InternalMessageInfo

func (m *NodeSpawnResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ClusterDeleteRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterDeleteRequest) Reset()         { *m = ClusterDeleteRequest{} }
func (m *ClusterDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterDeleteRequest) ProtoMessage()    {}
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{17}
}

func (m *ClusterDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterDeleteRequest.Unmarshal(m, b)
}
func (m *ClusterDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ClusterDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterDeleteRequest.Merge(m, src)
}
func (m *ClusterDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterDeleteRequest.Size(m)
}
func (m *ClusterDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterDeleteRequest proto.InternalMessageInfo

func (m *ClusterDeleteRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type ClusterDeleteResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterDeleteResponse) Reset()         { *m = ClusterDeleteResponse{} }
func (m *ClusterDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterDeleteResponse) ProtoMessage()    {}
func (*ClusterDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{18}
}

func (m *ClusterDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterDeleteResponse.Unmarshal(m, b)
}
func (m *ClusterDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ClusterDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterDeleteResponse.Merge(m, src)
}
func (m *ClusterDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterDeleteResponse.Size(m)
}
func (m *ClusterDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterDeleteResponse proto.InternalMessageInfo

func (m *ClusterDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NodeDeleteRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	NodeGroupName        string   `protobuf:"bytes,2,opt,name=nodeGroupName,proto3" json:"nodeGroupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDeleteRequest) Reset()         { *m = NodeDeleteRequest{} }
func (m *NodeDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*NodeDeleteRequest) ProtoMessage()    {}
func (*NodeDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{19}
}

func (m *NodeDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDeleteRequest.Unmarshal(m, b)
}
func (m *NodeDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDeleteRequest.Marshal(b, m, deterministic)
}
func (m *NodeDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDeleteRequest.Merge(m, src)
}
func (m *NodeDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_NodeDeleteRequest.Size(m)
}
func (m *NodeDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDeleteRequest proto.InternalMessageInfo

func (m *NodeDeleteRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *NodeDeleteRequest) GetNodeGroupName() string {
	if m != nil {
		return m.NodeGroupName
	}
	return ""
}

type NodeDeleteResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDeleteResponse) Reset()         { *m = NodeDeleteResponse{} }
func (m *NodeDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*NodeDeleteResponse) ProtoMessage()    {}
func (*NodeDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{20}
}

func (m *NodeDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDeleteResponse.Unmarshal(m, b)
}
func (m *NodeDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDeleteResponse.Marshal(b, m, deterministic)
}
func (m *NodeDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDeleteResponse.Merge(m, src)
}
func (m *NodeDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_NodeDeleteResponse.Size(m)
}
func (m *NodeDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDeleteResponse proto.InternalMessageInfo

func (m *NodeDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateVolumeRequest struct {
	Availabilityzone     string            `protobuf:"bytes,1,opt,name=availabilityzone,proto3" json:"availabilityzone,omitempty"`
	Volumetype           string            `protobuf:"bytes,2,opt,name=volumetype,proto3" json:"volumetype,omitempty"`
	Size                 int64             `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Snapshotid           string            `protobuf:"bytes,4,opt,name=snapshotid,proto3" json:"snapshotid,omitempty"`
	Provider             string            `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string            `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Labels               map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateVolumeRequest) Reset()         { *m = CreateVolumeRequest{} }
func (m *CreateVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeRequest) ProtoMessage()    {}
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{21}
}

func (m *CreateVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeRequest.Unmarshal(m, b)
}
func (m *CreateVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeRequest.Marshal(b, m, deterministic)
}
func (m *CreateVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeRequest.Merge(m, src)
}
func (m *CreateVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeRequest.Size(m)
}
func (m *CreateVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeRequest proto.InternalMessageInfo

func (m *CreateVolumeRequest) GetAvailabilityzone() string {
	if m != nil {
		return m.Availabilityzone
	}
	return ""
}

func (m *CreateVolumeRequest) GetVolumetype() string {
	if m != nil {
		return m.Volumetype
	}
	return ""
}

func (m *CreateVolumeRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateVolumeRequest) GetSnapshotid() string {
	if m != nil {
		return m.Snapshotid
	}
	return ""
}

func (m *CreateVolumeRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CreateVolumeRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CreateVolumeRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CreateVolumeResponse struct {
	Volumeid             string   `protobuf:"bytes,1,opt,name=volumeid,proto3" json:"volumeid,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVolumeResponse) Reset()         { *m = CreateVolumeResponse{} }
func (m *CreateVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeResponse) ProtoMessage()    {}
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{22}
}

func (m *CreateVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeResponse.Unmarshal(m, b)
}
func (m *CreateVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeResponse.Marshal(b, m, deterministic)
}
func (m *CreateVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeResponse.Merge(m, src)
}
func (m *CreateVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeResponse.Size(m)
}
func (m *CreateVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeResponse proto.InternalMessageInfo

func (m *CreateVolumeResponse) GetVolumeid() string {
	if m != nil {
		return m.Volumeid
	}
	return ""
}

func (m *CreateVolumeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteVolumeRequest struct {
	Volumeid             string   `protobuf:"bytes,1,opt,name=volumeid,proto3" json:"volumeid,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeRequest) Reset()         { *m = DeleteVolumeRequest{} }
func (m *DeleteVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeRequest) ProtoMessage()    {}
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{23}
}

func (m *DeleteVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeRequest.Unmarshal(m, b)
}
func (m *DeleteVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeRequest.Merge(m, src)
}
func (m *DeleteVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeRequest.Size(m)
}
func (m *DeleteVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeRequest proto.InternalMessageInfo

func (m *DeleteVolumeRequest) GetVolumeid() string {
	if m != nil {
		return m.Volumeid
	}
	return ""
}

func (m *DeleteVolumeRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *DeleteVolumeRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type DeleteVolumeResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeResponse) Reset()         { *m = DeleteVolumeResponse{} }
func (m *DeleteVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeResponse) ProtoMessage()    {}
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{24}
}

func (m *DeleteVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeResponse.Unmarshal(m, b)
}
func (m *DeleteVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeResponse.Merge(m, src)
}
func (m *DeleteVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeResponse.Size(m)
}
func (m *DeleteVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeResponse proto.InternalMessageInfo

func (m *DeleteVolumeResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DeleteVolumeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateSnapshotRequest struct {
	Volumeid             string            `protobuf:"bytes,1,opt,name=volumeid,proto3" json:"volumeid,omitempty"`
	Provider             string            `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateSnapshotRequest) Reset()         { *m = CreateSnapshotRequest{} }
func (m *CreateSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotRequest) ProtoMessage()    {}
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{25}
}

func (m *CreateSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotRequest.Unmarshal(m, b)
}
func (m *CreateSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *CreateSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotRequest.Merge(m, src)
}
func (m *CreateSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotRequest.Size(m)
}
func (m *CreateSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotRequest proto.InternalMessageInfo

func (m *CreateSnapshotRequest) GetVolumeid() string {
	if m != nil {
		return m.Volumeid
	}
	return ""
}

func (m *CreateSnapshotRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CreateSnapshotRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CreateSnapshotRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CreateSnapshotResponse struct {
	Snapshotid           string   `protobuf:"bytes,1,opt,name=snapshotid,proto3" json:"snapshotid,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSnapshotResponse) Reset()         { *m = CreateSnapshotResponse{} }
func (m *CreateSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotResponse) ProtoMessage()    {}
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{26}
}

func (m *CreateSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotResponse.Unmarshal(m, b)
}
func (m *CreateSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *CreateSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotResponse.Merge(m, src)
}
func (m *CreateSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotResponse.Size(m)
}
func (m *CreateSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotResponse proto.InternalMessageInfo

func (m *CreateSnapshotResponse) GetSnapshotid() string {
	if m != nil {
		return m.Snapshotid
	}
	return ""
}

func (m *CreateSnapshotResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateSnapshotAndDeleteRequest struct {
	Volumeid             string            `protobuf:"bytes,1,opt,name=volumeid,proto3" json:"volumeid,omitempty"`
	Provider             string            `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateSnapshotAndDeleteRequest) Reset()         { *m = CreateSnapshotAndDeleteRequest{} }
func (m *CreateSnapshotAndDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotAndDeleteRequest) ProtoMessage()    {}
func (*CreateSnapshotAndDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{27}
}

func (m *CreateSnapshotAndDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotAndDeleteRequest.Unmarshal(m, b)
}
func (m *CreateSnapshotAndDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotAndDeleteRequest.Marshal(b, m, deterministic)
}
func (m *CreateSnapshotAndDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotAndDeleteRequest.Merge(m, src)
}
func (m *CreateSnapshotAndDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotAndDeleteRequest.Size(m)
}
func (m *CreateSnapshotAndDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotAndDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotAndDeleteRequest proto.InternalMessageInfo

func (m *CreateSnapshotAndDeleteRequest) GetVolumeid() string {
	if m != nil {
		return m.Volumeid
	}
	return ""
}

func (m *CreateSnapshotAndDeleteRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CreateSnapshotAndDeleteRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CreateSnapshotAndDeleteRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CreateSnapshotAndDeleteResponse struct {
	Snapshotid           string   `protobuf:"bytes,1,opt,name=snapshotid,proto3" json:"snapshotid,omitempty"`
	Deleted              bool     `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSnapshotAndDeleteResponse) Reset()         { *m = CreateSnapshotAndDeleteResponse{} }
func (m *CreateSnapshotAndDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotAndDeleteResponse) ProtoMessage()    {}
func (*CreateSnapshotAndDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5725ddde20cc5ada, []int{28}
}

func (m *CreateSnapshotAndDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotAndDeleteResponse.Unmarshal(m, b)
}
func (m *CreateSnapshotAndDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotAndDeleteResponse.Marshal(b, m, deterministic)
}
func (m *CreateSnapshotAndDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotAndDeleteResponse.Merge(m, src)
}
func (m *CreateSnapshotAndDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotAndDeleteResponse.Size(m)
}
func (m *CreateSnapshotAndDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotAndDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotAndDeleteResponse proto.InternalMessageInfo

func (m *CreateSnapshotAndDeleteResponse) GetSnapshotid() string {
	if m != nil {
		return m.Snapshotid
	}
	return ""
}

func (m *CreateSnapshotAndDeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *CreateSnapshotAndDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeSpec)(nil), "pb.NodeSpec")
	proto.RegisterMapType((map[string]string)(nil), "pb.NodeSpec.LabelsEntry")
	proto.RegisterType((*ClusterRequest)(nil), "pb.ClusterRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.ClusterRequest.LabelsEntry")
	proto.RegisterType((*GetClusterRequest)(nil), "pb.GetClusterRequest")
	proto.RegisterType((*GetClustersRequest)(nil), "pb.GetClustersRequest")
	proto.RegisterType((*ClusterSpec)(nil), "pb.ClusterSpec")
	proto.RegisterType((*GetClustersResponse)(nil), "pb.GetClustersResponse")
	proto.RegisterType((*ClusterResponse)(nil), "pb.ClusterResponse")
	proto.RegisterType((*ClusterStatusRequest)(nil), "pb.ClusterStatusRequest")
	proto.RegisterType((*ClusterStatusResponse)(nil), "pb.ClusterStatusResponse")
	proto.RegisterType((*AddTokenRequest)(nil), "pb.AddTokenRequest")
	proto.RegisterType((*AddTokenResponse)(nil), "pb.AddTokenResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "pb.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "pb.GetTokenResponse")
	proto.RegisterType((*AddRoute53RecordRequest)(nil), "pb.AddRoute53RecordRequest")
	proto.RegisterType((*AddRoute53RecordResponse)(nil), "pb.AddRoute53RecordResponse")
	proto.RegisterType((*NodeSpawnRequest)(nil), "pb.NodeSpawnRequest")
	proto.RegisterType((*NodeSpawnResponse)(nil), "pb.NodeSpawnResponse")
	proto.RegisterType((*ClusterDeleteRequest)(nil), "pb.ClusterDeleteRequest")
	proto.RegisterType((*ClusterDeleteResponse)(nil), "pb.ClusterDeleteResponse")
	proto.RegisterType((*NodeDeleteRequest)(nil), "pb.NodeDeleteRequest")
	proto.RegisterType((*NodeDeleteResponse)(nil), "pb.NodeDeleteResponse")
	proto.RegisterType((*CreateVolumeRequest)(nil), "pb.CreateVolumeRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateVolumeRequest.LabelsEntry")
	proto.RegisterType((*CreateVolumeResponse)(nil), "pb.CreateVolumeResponse")
	proto.RegisterType((*DeleteVolumeRequest)(nil), "pb.DeleteVolumeRequest")
	proto.RegisterType((*DeleteVolumeResponse)(nil), "pb.DeleteVolumeResponse")
	proto.RegisterType((*CreateSnapshotRequest)(nil), "pb.CreateSnapshotRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateSnapshotRequest.LabelsEntry")
	proto.RegisterType((*CreateSnapshotResponse)(nil), "pb.CreateSnapshotResponse")
	proto.RegisterType((*CreateSnapshotAndDeleteRequest)(nil), "pb.CreateSnapshotAndDeleteRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateSnapshotAndDeleteRequest.LabelsEntry")
	proto.RegisterType((*CreateSnapshotAndDeleteResponse)(nil), "pb.CreateSnapshotAndDeleteResponse")
}

func init() { proto.RegisterFile("spawnersvc.proto", fileDescriptor_5725ddde20cc5ada) }

var fileDescriptor_5725ddde20cc5ada = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x29, 0x4b, 0x96, 0x47, 0x89, 0xad, 0xac, 0x65, 0x9b, 0x61, 0x03, 0xd7, 0x60, 0x5a,
	0xc0, 0x4d, 0x51, 0xb5, 0x70, 0x90, 0xd4, 0x4d, 0x11, 0x20, 0x8a, 0x1b, 0x3b, 0x41, 0x0b, 0x17,
	0xa0, 0x8a, 0x1e, 0x5a, 0x20, 0x00, 0xa5, 0x5d, 0xd4, 0x84, 0x15, 0x92, 0xe1, 0x52, 0x0a, 0x1c,
	0xf4, 0xe5, 0xfa, 0x00, 0x7d, 0x88, 0x9e, 0x7b, 0xec, 0xb1, 0x97, 0x62, 0xff, 0xc8, 0x5d, 0x8a,
	0x74, 0x64, 0x43, 0xbd, 0x71, 0x66, 0x77, 0xfe, 0xbe, 0x99, 0x9d, 0x19, 0x09, 0xba, 0x34, 0x09,
	0xde, 0x45, 0x24, 0xa5, 0xb3, 0x71, 0x3f, 0x49, 0xe3, 0x2c, 0x46, 0x76, 0x32, 0xf2, 0xfe, 0xb6,
	0xa1, 0x7d, 0x16, 0x63, 0x32, 0x4c, 0xc8, 0x18, 0x21, 0x58, 0x8d, 0x82, 0x37, 0xc4, 0xb1, 0xf6,
	0xad, 0x83, 0x75, 0x9f, 0x7f, 0x23, 0x17, 0xda, 0x61, 0x44, 0xb3, 0x20, 0x1a, 0x13, 0xc7, 0xe6,
	0xfc, 0x9c, 0x66, 0x67, 0x38, 0xa4, 0x17, 0xc3, 0xf0, 0x3d, 0x71, 0x1a, 0xfb, 0xd6, 0x41, 0xd3,
	0xcf, 0x69, 0x76, 0x76, 0x1e, 0xd3, 0xec, 0x8c, 0xe9, 0x5b, 0x15, 0x72, 0x8a, 0x46, 0x3d, 0x68,
	0xd2, 0x2c, 0xc8, 0x88, 0xd3, 0xe4, 0x07, 0x82, 0x60, 0xd6, 0xa7, 0xd3, 0x10, 0x3b, 0x2d, 0x61,
	0x9d, 0x7d, 0xa3, 0x1d, 0x68, 0x85, 0xc9, 0x00, 0xe3, 0xd4, 0x59, 0xe3, 0x5c, 0x49, 0xa1, 0x07,
	0xd0, 0x0d, 0x66, 0x41, 0x38, 0x09, 0x46, 0xe1, 0x24, 0xcc, 0x2e, 0xdf, 0xc7, 0x11, 0x71, 0xda,
	0xfc, 0xc6, 0x1c, 0x1f, 0xdd, 0x83, 0xf5, 0xf1, 0x64, 0x4a, 0x33, 0x92, 0xbe, 0xc2, 0xce, 0x3a,
	0xbf, 0x54, 0x30, 0xd0, 0x57, 0xd0, 0x9a, 0x04, 0x23, 0x32, 0xa1, 0x0e, 0xec, 0x37, 0x0e, 0x3a,
	0x87, 0x4e, 0x3f, 0x19, 0xf5, 0x15, 0x22, 0xfd, 0x1f, 0xf8, 0xd1, 0x8b, 0x28, 0x4b, 0x2f, 0x7d,
	0x79, 0xcf, 0xfd, 0x06, 0x3a, 0x1a, 0x1b, 0x75, 0xa1, 0x71, 0x41, 0x2e, 0x25, 0x66, 0xec, 0x93,
	0x85, 0x37, 0x0b, 0x26, 0x53, 0x85, 0x97, 0x20, 0x9e, 0xd8, 0x47, 0x96, 0xf7, 0xaf, 0x05, 0x1b,
	0xc7, 0xc2, 0xb4, 0x4f, 0xde, 0x4e, 0x09, 0xcd, 0xd0, 0x3e, 0x74, 0xa4, 0x33, 0x67, 0x05, 0xf4,
	0x3a, 0x8b, 0x21, 0x99, 0xa4, 0xf1, 0x2c, 0xc4, 0x24, 0x55, 0x19, 0x50, 0x34, 0xc3, 0x27, 0x25,
	0xbf, 0x85, 0x71, 0xc4, 0xf1, 0x5f, 0xf7, 0x25, 0x85, 0xf6, 0x61, 0x35, 0x8a, 0xb1, 0x40, 0xbe,
	0x73, 0x78, 0x4b, 0x8f, 0xc9, 0xe7, 0x27, 0xe8, 0x71, 0x1e, 0x77, 0x93, 0xc7, 0xbd, 0xc7, 0xee,
	0x98, 0xbe, 0x2d, 0x3b, 0xfa, 0x47, 0x70, 0xe7, 0x94, 0x64, 0xd7, 0x8d, 0xdf, 0x7b, 0x0d, 0xa8,
	0x10, 0xa3, 0x4a, 0x4e, 0x47, 0xc5, 0xaa, 0x45, 0xc5, 0x36, 0x50, 0x61, 0x75, 0x37, 0x8e, 0x13,
	0x22, 0xc1, 0x12, 0x84, 0x17, 0x42, 0x47, 0x2a, 0xaf, 0x7d, 0x04, 0x46, 0x09, 0xd9, 0xe5, 0x12,
	0x3a, 0x80, 0x76, 0x24, 0xc1, 0x75, 0x1a, 0x1c, 0x4c, 0x13, 0xf0, 0xfc, 0xd4, 0x7b, 0x0e, 0x5b,
	0x46, 0x28, 0x34, 0x89, 0x23, 0x4a, 0xd0, 0xe7, 0xd0, 0x96, 0xda, 0xa8, 0x63, 0x71, 0x05, 0x9b,
	0x5a, 0x36, 0x84, 0x0e, 0x75, 0xc1, 0x8b, 0x61, 0x33, 0x87, 0x50, 0xca, 0x7f, 0xb8, 0x86, 0x3e,
	0x81, 0xdb, 0xcc, 0x89, 0xd3, 0x34, 0x9e, 0x26, 0xfc, 0x8e, 0x08, 0xc2, 0x64, 0x32, 0x7c, 0x48,
	0x9a, 0xc6, 0xa9, 0xc2, 0x87, 0x13, 0xde, 0x11, 0xf4, 0x94, 0x27, 0x59, 0x90, 0x4d, 0xe9, 0xe2,
	0x99, 0x7b, 0x01, 0xdb, 0x25, 0x49, 0xe9, 0xf0, 0x0e, 0xb4, 0x28, 0xe7, 0x48, 0x29, 0x49, 0x15,
	0x0e, 0xd8, 0xba, 0x03, 0xdf, 0xc3, 0xe6, 0x00, 0xe3, 0x9f, 0xe2, 0x0b, 0x12, 0x2d, 0xfe, 0x6a,
	0x6a, 0x6a, 0xc0, 0x7b, 0x06, 0xdd, 0x42, 0xd9, 0x4d, 0xdd, 0x39, 0x25, 0xd9, 0x92, 0xdc, 0xf9,
	0x1d, 0xba, 0x85, 0x32, 0xe9, 0x4e, 0x0f, 0x9a, 0x19, 0x63, 0x48, 0x3d, 0x82, 0x60, 0x29, 0x4c,
	0x83, 0x68, 0x7c, 0x4e, 0xd2, 0x21, 0x49, 0x67, 0x79, 0x2f, 0x30, 0x99, 0x5a, 0x28, 0x8d, 0xea,
	0x50, 0x56, 0xf5, 0x50, 0x28, 0xec, 0x0e, 0x30, 0xf6, 0xe3, 0x69, 0x46, 0x1e, 0x3d, 0xf4, 0xc9,
	0x38, 0x4e, 0xb1, 0x0a, 0xc9, 0x81, 0x35, 0x1c, 0x51, 0x2d, 0x1c, 0x45, 0xa2, 0x3d, 0x80, 0x94,
	0x5f, 0xd5, 0x0a, 0x49, 0xe3, 0x88, 0x73, 0x16, 0x1c, 0x3f, 0x6f, 0xa8, 0x73, 0xc5, 0xf1, 0x5e,
	0x82, 0x33, 0x6f, 0xf4, 0x46, 0x99, 0x78, 0x0d, 0x5d, 0xf1, 0xc8, 0x82, 0x77, 0xd7, 0x48, 0x85,
	0xfe, 0x5c, 0xed, 0x8a, 0xfe, 0x58, 0x3c, 0xd7, 0xcf, 0xe0, 0x8e, 0xa6, 0xbf, 0xc8, 0x4e, 0x85,
	0x2b, 0xc5, 0x23, 0xf9, 0x8e, 0x4c, 0x48, 0x46, 0x16, 0x7f, 0x24, 0x5f, 0xe4, 0x8f, 0x44, 0x49,
	0x96, 0x0d, 0x59, 0xba, 0xa1, 0x5f, 0x85, 0x4f, 0xd7, 0xb4, 0xb2, 0x58, 0x03, 0xf0, 0x1e, 0x00,
	0xd2, 0x95, 0x5f, 0xe9, 0xc8, 0x1f, 0x36, 0x6c, 0x1d, 0xa7, 0x24, 0xc8, 0xc8, 0xcf, 0xf1, 0x64,
	0xfa, 0x26, 0xf7, 0xa5, 0x6a, 0x34, 0x5b, 0x35, 0xa3, 0x79, 0x0f, 0x60, 0xc6, 0x85, 0xb3, 0xcb,
	0x24, 0x2f, 0xa5, 0x82, 0xc3, 0x7a, 0x31, 0x55, 0xcb, 0x45, 0xc3, 0xe7, 0xdf, 0x4c, 0x86, 0x46,
	0x41, 0x42, 0xcf, 0xe3, 0x2c, 0xc4, 0xb2, 0x9c, 0x35, 0x8e, 0x31, 0x18, 0x9a, 0xb5, 0x83, 0xa1,
	0x65, 0x0c, 0x86, 0x6f, 0xf3, 0x61, 0xb8, 0xc6, 0xdb, 0xef, 0x7d, 0xde, 0x7e, 0xe7, 0x83, 0x5b,
	0xf6, 0x44, 0x7c, 0x09, 0x3d, 0xd3, 0x8a, 0x44, 0xdc, 0x85, 0xb6, 0x40, 0x21, 0xc4, 0x6a, 0xb8,
	0x29, 0xba, 0xa6, 0xfe, 0x08, 0x6c, 0x89, 0xac, 0x99, 0xc9, 0xb8, 0x4a, 0xd1, 0x0d, 0xf6, 0x0a,
	0xef, 0x04, 0x7a, 0xa6, 0x19, 0xe9, 0x30, 0xeb, 0x16, 0x9c, 0x2f, 0xcc, 0xb4, 0x7d, 0x45, 0xd6,
	0xb8, 0xfb, 0x97, 0x05, 0xdb, 0x22, 0xf2, 0xa1, 0xcc, 0xdc, 0xff, 0xe4, 0x31, 0x7a, 0x9a, 0xa7,
	0x76, 0x95, 0xa7, 0xf6, 0xd3, 0x22, 0xb5, 0x25, 0xd3, 0xcb, 0x4e, 0xee, 0x19, 0xec, 0x94, 0xed,
	0x48, 0xb4, 0xcc, 0x12, 0xb6, 0xe6, 0x4a, 0xb8, 0x1a, 0xb3, 0x7f, 0x2c, 0xd8, 0x33, 0x15, 0x0e,
	0x22, 0x6c, 0xf6, 0x81, 0x65, 0x83, 0x77, 0x52, 0x02, 0xaf, 0x3f, 0x0f, 0x5e, 0xd9, 0x87, 0x65,
	0xa3, 0xf8, 0x16, 0x3e, 0xae, 0x35, 0xb8, 0x20, 0x9c, 0x5a, 0x71, 0xda, 0x35, 0xc5, 0xa9, 0x2f,
	0x3c, 0x87, 0x7f, 0xae, 0xc1, 0xc6, 0x50, 0xfc, 0x58, 0x62, 0x53, 0x35, 0x1c, 0x13, 0xf4, 0x04,
	0x6e, 0x0b, 0x2f, 0x64, 0xab, 0x46, 0x68, 0x7e, 0x5d, 0x76, 0xb7, 0x0c, 0x9e, 0x70, 0xce, 0x5b,
	0x41, 0x5f, 0x43, 0x5b, 0x6d, 0x1c, 0x88, 0x5f, 0x29, 0x2d, 0x33, 0x6e, 0xcf, 0x64, 0xea, 0x82,
	0x6a, 0x37, 0x10, 0x82, 0xa5, 0xb5, 0x43, 0x08, 0x96, 0xd7, 0x07, 0x6f, 0x05, 0xfd, 0xc8, 0x77,
	0x1c, 0x63, 0xc2, 0xa2, 0x8f, 0xa4, 0x91, 0xaa, 0x61, 0xef, 0xde, 0xab, 0x3e, 0xcc, 0x15, 0x3e,
	0x06, 0x28, 0xf6, 0x56, 0xb4, 0x2d, 0xcd, 0x96, 0xc2, 0x2f, 0xef, 0xac, 0xde, 0x0a, 0x7a, 0x06,
	0x1d, 0x6d, 0xdf, 0x45, 0x3b, 0xa6, 0xa0, 0xda, 0x24, 0xdd, 0xdd, 0x39, 0x7e, 0x6e, 0xf9, 0x08,
	0xd6, 0x06, 0x18, 0xb3, 0xa1, 0x84, 0x7a, 0xc5, 0x94, 0x2e, 0xe6, 0xbd, 0xbb, 0x5d, 0xe2, 0xe6,
	0x92, 0x27, 0x70, 0xdb, 0x58, 0x3e, 0x91, 0xa3, 0xfb, 0xa7, 0x6f, 0xb2, 0xee, 0xdd, 0x8a, 0x13,
	0x5d, 0x8f, 0xa8, 0x37, 0x15, 0xbe, 0xae, 0xc7, 0x28, 0x7d, 0x43, 0x8f, 0x59, 0xa3, 0xde, 0x0a,
	0x7a, 0x0a, 0x20, 0x78, 0x3c, 0x98, 0xdc, 0x6d, 0x53, 0xc3, 0x4e, 0x99, 0x9d, 0x8b, 0x1f, 0xc3,
	0x2d, 0x7d, 0x54, 0xa0, 0xdd, 0x9a, 0x11, 0xe5, 0x3a, 0xf3, 0x07, 0xba, 0x12, 0xbd, 0x7d, 0x0b,
	0x25, 0x15, 0x73, 0x43, 0x28, 0xa9, 0xea, 0xf4, 0xde, 0x0a, 0x7a, 0x05, 0x1b, 0xe6, 0x8b, 0x44,
	0x77, 0x6b, 0x7b, 0xaa, 0xeb, 0x56, 0x1d, 0xe5, 0xaa, 0x30, 0xec, 0xd6, 0x3c, 0x6e, 0xe4, 0x7d,
	0xb8, 0xd5, 0xb8, 0xf7, 0xaf, 0xbc, 0xa3, 0xac, 0x3c, 0x6f, 0xfe, 0xd2, 0xf8, 0x32, 0x19, 0x8d,
	0x5a, 0xfc, 0x5f, 0x8f, 0x87, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x50, 0x4e, 0x0a, 0x09,
	0x11, 0x00, 0x00,
}
